// node spots_seed.js

const db = require('../config/keys').mongoURI;
const mongoose = require('mongoose');
const Spot = require('../models/Spot');
const Image = require('../models/Image');
const ObjectId = mongoose.Types.ObjectId;

mongoose
.connect(db, { useNewUrlParser: true })
.then((database) => {
  Spot.remove({}).then( () => {
    let spotsIds = [];
    let img1Ids = [];
    let img2Ids = [];
    for(let i = 0; i < 50; i++) {
      spotsIds.push(ObjectId());
      img1Ids.push(ObjectId());
      img2Ids.push(ObjectId());
    }

    Spot.create(
      [
        { _id: spotsIds[0], images: [img1Ids[0], img2Ids[0]], host_id: 1, name: 'Private Room @ Social SF Hostel', description: 'Our social and vibrant hostel in downtown SF is the place to stay! We invite travelers and adventurers of all ages, from all corners of the globe, to rest their heads at this historic hostel in the heart of San Francisco. We pride ourselves on creating a community vibe and a space that encourages guests to gather together, exchange travel stories, and get to know one another.', lat: 37.7981734, lng: -122.4089941, street_address: '310 Columbus Ave', city: 'San Francisco', state: 'CA', zip: 94107, price: 501, occupancy: 2, date: new Date() },
        { _id: spotsIds[1], images: [img1Ids[1], img2Ids[1]], host_id: 2, name: 'Triple Room @ Fun & Social Hostel#1', description: 'Our social and vibrant hostel in downtown SF is the place to stay! We invite travelers and adventurers of all ages, from all corners of the globe, to rest their heads at this historic hostel in the heart of San Francisco. We pride ourselves on creating a community vibe and a space that encourages guests to gather together, exchange travel stories, and get to know one another.', lat: 37.8074862, lng: -122.4226541, street_address: '495 Jefferson St', city: 'San Francisco', state: 'CA', zip: 94108, price: 260, occupancy: 2, date: new Date() },
        { _id: spotsIds[2], images: [img1Ids[2], img2Ids[2]], host_id: 3, name: 'Friendly Hostel with Community #3', description: 'We are a hostel specifically designed for social, friendly backpackers, world travelers, & wanderlust seekers. We are sanctioned by the San Francisco planning commission to provide tourist accommodation and have been a top rated hostel for 25 years! We offer mixed gender dorms, clean bathrooms, fully stocked kitchen, and a common room full of new friends in downtown SF. Come join us!', lat: 37.8072961, lng: -122.4151182, street_address: '2500 Mason St', city: 'San Francisco', state: 'CA', zip: 94108, price: 327, occupancy: 3, date: new Date() },
        { _id: spotsIds[3], images: [img1Ids[3], img2Ids[3]], host_id: 4, name: 'Condo in Nob Hill/ view of the Golden Gate Bridge', description: 'Located in the heart of San Francisco, you can enjoy a great view of the Golden Gate Bridge from the comfort of the living room or on the roof where there is a fire pit and BBQ with comfy couches.', lat: 37.8056509, lng: -122.4197832, street_address: '1250 Columbus Ave', city: 'San Francisco', state: 'CA', zip: 94108, price: 277, occupancy: 4, date: new Date() },
        { _id: spotsIds[4], images: [img1Ids[4], img2Ids[4]], host_id: 5, name: 'Heritage', description: 'Very central so walking distance to the popular bars and restaurants on Polk street and also walking distance to the financial district if you are here on business. A block away from the cable car and bus line.', lat: 37.8056739, lng: -122.4245703, street_address: '900 North Point St d100', city: 'San Francisco', state: 'CA', zip: 94108, price: 345, occupancy: 3, date: new Date() },
        { _id: spotsIds[5], images: [img1Ids[5], img2Ids[5]], host_id: 6, name: 'Room in San Francisco’s beautiful', description: 'Hi there! Hope you ll be staying with us soon. Our cozy apartment in picturesque Nob Hill is centrally located and a great home base for your trip to San Francisco. While my fiance and I are New York transplants, we re happy to answer any questions you may have about our adopted city and will do our best to ensure that you have a great stay. We re an open and accepting household and all backgrounds are welcome - looking forward to meeting you!', lat: 37.8053237, lng: -122.4201402, street_address: '1201 Columbus Ave', city: 'San Francisco', state: 'CA', zip: 94108, price: 288, occupancy: 3, date: new Date() },
        { _id: spotsIds[6], images: [img1Ids[6], img2Ids[6]], host_id: 7, name: 'Dorm Beds @ Social SF Hostel #6', description: 'Our social and vibrant hostel in downtown SF is the place to stay! We invite travelers and adventurers of all ages, from all corners of the globe, to rest their heads at this historic hostel in the heart of San Francisco. We pride ourselves on creating a community vibe and a space that encourages guests to gather together, exchange travel stories, and get to know one another.', lat: 37.8077627, lng: -122.4154157, street_address: '250 Beach St', city: 'San Francisco', state: 'CA', zip: 94108, price: 253, occupancy: 3, date: new Date() },
        { _id: spotsIds[7], images: [img1Ids[7], img2Ids[7]], host_id: 8, name: 'Hilltop Haven-Premier View Accelerator Queen', description: 'Conde Nast Traveler 2018 Readers Choice Awards #2 San Francisco Hotel! A delightful blend of escape & access, our location atop the prized Nob Hill offers spectacular views, the city s three cable car lines, and is conveniently just blocks from Union Square. Our cozy residential accommodations offer true respite from a supercharged day of exploring our vibrant neighborhoods. Sleek minimalist décor of the room features unique and custom-designed furnishings.', lat: 37.8043012, lng: -122.4157819, street_address: '2237 Mason St', city: 'San Francisco', state: 'CA', zip: 94108, price: 304, occupancy: 2, date: new Date() },
        { _id: spotsIds[8], images: [img1Ids[8], img2Ids[8]], host_id: 9, name: '2-bedroom Apartment', description: 'Can accommodate up to six guests. This apartment offers two individual bedrooms separate from the living room, each featuring a private en suite bathroom. It also include a living room and fireplace, modern fully equipped kitchen, a private washer and dryer, and a pullout sofa. 1,200+ sqft.', lat: 37.7983824, lng: -122.4489536, street_address: '2755 Lombard St', city: 'San Francisco', state: 'CA', zip: 94108, price: 535, occupancy: 4, date: new Date() },
        { _id: spotsIds[9], images: [img1Ids[9], img2Ids[9]], host_id: 10, name: '2-bedroom Apartment - Bay View', description: 'Can accommodate up to six guests. This apartment offers luxurious accommodations with beautiful views of the bay. It carries two individual bedrooms separate from the living room, each featuring a private en suite bathroom. The contemporary style living room encompasses a fire place and a rare façade with the original brick wall from the Historical Ghirardelli Chocolate factory. It also include a modern fully equipped kitchen, a private washer and dryer, and a pullout sofa.', lat: 37.799006, lng: -122.4461892, street_address: '2576 Lombard St', city: 'San Francisco', state: 'CA', zip: 94108, price: 292, occupancy: 3, date: new Date() },
        { _id: spotsIds[10], images: [img1Ids[10], img2Ids[10]], host_id: 11, name: 'Triple Room @ Fun & Social Hostel #3', description: 'Our social and vibrant hostel in downtown SF is the place to stay! We invite travelers and adventurers of all ages, from all corners of the globe, to rest their heads at this historic hostel in the heart of San Francisco. We pride ourselves on creating a community vibe and a space that encourages guests to gather together, exchange travel stories, and get to know one another.', lat: 37.7993159, lng: -122.4438972, street_address: '2440 Lombard St', city: 'San Francisco', state: 'CA', zip: 94108, price: 269, occupancy: 4, date: new Date() },
        { _id: spotsIds[11], images: [img1Ids[11], img2Ids[11]], host_id: 12, name: 'Hilltop Haven- Deluxe Incubator King', description: 'Conde Nast Traveler 2018 Readers Choice Awards #2 San Francisco Hotel! A delightful blend of escape & access, our location atop the prized Nob Hill offers spectacular views, the city s three cable car lines, and is conveniently just blocks from Union Square.Our cozy residential accommodations offer true respite from a supercharged day of exploring our vibrant neighborhoods.Sleek minimalist décor of the room features unique and custom - designed furnishings.', lat: 37.7988671, lng: -122.439916, street_address: '3201 Steiner St', city: 'San Francisco', state: 'CA', zip: 94108, price: 474, occupancy: 3, date: new Date() },
        { _id: spotsIds[12], images: [img1Ids[12], img2Ids[12]], host_id: 13, name: 'Hilltop Haven- Deluxe Incubator Queen', description: 'Conde Nast Traveler 2018 Readers Choice Awards #2 San Francisco Hotel! A delightful blend of escape & access, our location atop the prized Nob Hill offers spectacular views, the city s three cable car lines, and is conveniently just blocks from Union Square.Our cozy residential accommodations offer true respite from a supercharged day of exploring our vibrant neighborhoods.Sleek minimalist décor of the room features unique and custom - designed furnishings.', lat: 37.7998846, lng: -122.4396291, street_address: '2190 Lombard St', city: 'San Francisco', state: 'CA', zip: 94108, price: 366, occupancy: 3, date: new Date() },
        { _id: spotsIds[13], images: [img1Ids[13], img2Ids[13]], host_id: 14, name: 'Friendly Hostel with Community #11', description: 'We are a hostel specifically designed for social, friendly backpackers, world travelers, & wanderlust seekers.We are sanctioned by the San Francisco planning commission to provide tourist accommodation and have been a top rated hostel for 25 years! We offer mixed gender dorms, clean bathrooms, fully stocked kitchen, and a common room full of new friends in downtown SF.Come join us!', lat: 37.7996304, lng: -122.4378589, street_address: '2095 Lombard St', city: 'San Francisco', state: 'CA', zip: 94108, price: 445, occupancy: 4, date: new Date() },
        { _id: spotsIds[14], images: [img1Ids[14], img2Ids[14]], host_id: 15, name: 'Stunning Bay View! Prime North Beach Location!', description: 'San Francisco at your doorstep! Top floor with exquisite balcony! In the heart of the Italian District, this upmarket character Apartment is a stones throw from the cities best restaurants, attractions, North Beach!!!', lat: 37.7993682, lng: -122.4361115, street_address: '3100 Webster St', city: 'San Francisco', state: 'CA', zip: 94108, price: 427, occupancy: 2, date: new Date() },
        { _id: spotsIds[15], images: [img1Ids[15], img2Ids[15]], host_id: 16, name: 'Friendly Hostel with Community #12', description: 'We are a hostel specifically designed for social, friendly backpackers, world travelers, & wanderlust seekers. We are sanctioned by the San Francisco planning commission to provide tourist accommodation and have been a top rated hostel for 25 years! We offer mixed gender dorms, clean bathrooms, fully stocked kitchen, and a common room full of new friends in downtown SF. Come join us!', lat: 37.7990452, lng: -122.4352268, street_address: '2015 Greenwich St', city: 'San Francisco', state: 'CA', zip: 94107, price: 532, occupancy: 2, date: new Date() },
        { _id: spotsIds[16], images: [img1Ids[16], img2Ids[16]], host_id: 17, name: 'NEW! Private Bedroom in the Heart of the City', description: 'Spend a night or two in my newly remodeled apartment right in downtown San Francisco. Perfectly located super close to the hottest spots in town, walking distance to Union Square, shopping, and plenty of restaurants!', lat: 37.800509, lng: -122.4356691, street_address: '1940 Lombard St', city: 'San Francisco', state: 'CA', zip: 94107, price: 499, occupancy: 4, date: new Date() },
        { _id: spotsIds[17], images: [img1Ids[17], img2Ids[17]], host_id: 18, name: 'Condo in Nob Hill/ view of the Golden Gate Bridge', description: 'Located in the heart of San Francisco, you can enjoy a great view of the Golden Gate Bridge from the comfort of the living room or on the roof where there is a fire pit and BBQ with comfy couches.', lat: 37.8011334, lng: -122.4309797, street_address: '1650 Lombard St', city: 'San Francisco', state: 'CA', zip: 94107, price: 269, occupancy: 2, date: new Date() },
        { _id: spotsIds[18], images: [img1Ids[18], img2Ids[18]], host_id: 19, name: 'Friendly Hostel with Community #3', description: 'We are a hostel specifically designed for social, friendly backpackers, world travelers, & wanderlust seekers. We are sanctioned by the San Francisco planning commission to provide tourist accommodation and have been a top rated hostel for 25 years! We offer mixed gender dorms, clean bathrooms, fully stocked kitchen, and a common room full of new friends in downtown SF. Come join us!', lat: 37.7982617, lng: -122.4271307, street_address: '1555 Union St', city: 'San Francisco', state: 'CA', zip: 94107, price: 546, occupancy: 3, date: new Date() },
        { _id: spotsIds[19], images: [img1Ids[19], img2Ids[19]], host_id: 20, name: 'Hilltop Haven-Premier View Accelerator Queen', description: 'A delightful blend of escape & access, our location atop the prized Nob Hill offers spectacular views, the city s three cable car lines, and is conveniently just blocks from Union Square. Our cozy residential accommodations offer true respite from a supercharged day of exploring our vibrant neighborhoods. Sleek minimalist décor of the room features unique and custom-designed furnishings.', lat: 37.7958447, lng: -122.4261574, street_address: '2201 Van Ness Ave', city: 'San Francisco', state: 'CA', zip: 94107, price: 352, occupancy: 3, date: new Date() },
        { _id: spotsIds[20], images: [img1Ids[20], img2Ids[20]], host_id: 21, name: '(the 15) Private Room Near Downtown SF', description: 'Come stay in a dorm like style apartment. A private room with queen size bed & a pristine shared bathroom located in the hall. You are steps away from bars and clubs. Not to mention the beautiful Union Square shopping is only a 10 minute walk away!', lat: 37.7876353, lng: -122.4488364, street_address: '444 Presidio Ave', city: 'San Francisco', state: 'CA', zip: 94107, price: 512, occupancy: 4, date: new Date() },
        { _id: spotsIds[21], images: [img1Ids[21], img2Ids[21]], host_id: 22, name: 'Spring Room (12)', description: 'Come stay in a dorm like style apartment. A private room with queen size bed & a pristine shared bathroom located in the hall. You are steps away from bars and clubs. Not to mention the beautiful Union Square shopping is only a 10 minute walk away!', lat: 37.7791236, lng: -122.4358541, street_address: '1057 Steiner St', city: 'San Francisco', state: 'CA', zip: 94107, price: 542, occupancy: 4, date: new Date() },
        { _id: spotsIds[22], images: [img1Ids[22], img2Ids[22]], host_id: 23, name: 'Room in San Francisco’s beautiful Nob Hill', description: 'Hi there! Hope you ll be staying with us soon. Our cozy apartment in picturesque Nob Hill is centrally located and a great home base for your trip to San Francisco. While my fiance and I are New York transplants, we re happy to answer any questions you may have about our adopted city and will do our best to ensure that you have a great stay. We re an open and accepting household and all backgrounds are welcome - looking forward to meeting you!', lat: 37.7724869, lng: -122.4397501, street_address: '319 Divisadero St', city: 'San Francisco', state: 'CA', zip: 94107, price: 260, occupancy: 3, date: new Date() },
        { _id: spotsIds[23], images: [img1Ids[23], img2Ids[23]], host_id: 24, name: 'Ballpark & Sf Downtown Private Hotel Bedrm', description: 'My place is good for couples, solo adventurers, business travelers, and big groups. My place is good for solo adventurers & business travelers. Located in the heart of Soma district. If u walk outside, you can see the ballpark. We are 3 blocks away from the SF ATT Ballpark stadium. Everything else is close proximity to Caltrain, Bart, Union Square shopping, and the front bus line brings you directly to Chinatown, North Beach, Fisherman Wharf, & into the Marina where Golden gate bridge is', lat: 37.7681367, lng: -122.4553574, street_address: '750 Stanyan St', city: 'San Francisco', state: 'CA', zip: 94107, price: 460, occupancy: 3, date: new Date() },
        { _id: spotsIds[24], images: [img1Ids[24], img2Ids[24]], host_id: 25, name: 'Private Room with shared bathroom in Hotel', description: 'Hotel in Tenderloin about 4 blocks from Downtown/Union Square and Shopping Center. Public Transportation is at every block and Moscone Center is a 10 min walk. You’ll love my place because of Convenience and it s good for all travelers. Our hotel is centrally located to everything you could possibly think of however there is a church/shelter a block away which gets the sidewalk filled with homeless people. Since our location is close to downtown the streets may get a little noisy and dirty.', lat: 37.7667976, lng: -122.4324802, street_address: '2162 Market St', city: 'San Francisco', state: 'CA', zip: 94107, price: 501, occupancy: 2, date: new Date() },
        { _id: spotsIds[25], images: [img1Ids[25], img2Ids[25]], host_id: 26, name: 'ATT Ballpark private hotel bedrm in Soma', description: 'My place is good for solo adventurers & business travelers. Located in heart of Soma district. We are close to SF ATT ballpark, Caltrain, Whole Foods, Moscone Center, Safeway, Walgreens, Starbucks, Union Square, Bart and Muni bus line out front. If you walk outside, you can see the Ballpark. We are 3 blocks away fro the ballpark stadium. Everything else is in close proximity: supermarkets, convenience stores, and plenty of restaurants and bars to pick and choose from.', lat: 37.7625044, lng: -122.430847, street_address: '520 Church St, San Francisco, CA 94114', city: 'San Francisco', state: 'CA', zip: 94107, price: 473, occupancy: 2, date: new Date() },
        { _id: spotsIds[26], images: [img1Ids[26], img2Ids[26]], host_id: 27, name: 'Winter Room (8)', description: 'Come stay in a dorm like style apartment. A private room with queen size bed & a pristine shared bathroom located in the hall. You are steps away from bars and clubs. Not to mention the beautiful Union Square shopping is only a 5 minute walk away!', lat: 37.7658056, lng: -122.4239222, street_address: '447 Valencia St', city: 'San Francisco', state: 'CA', zip: 94107, price: 450, occupancy: 3, date: new Date() },
        { _id: spotsIds[27], images: [img1Ids[27], img2Ids[27]], host_id: 28, name: 'CALEF HOUSE Rm 3 in Beaut SF Vict!', description: 'A sunny ample corner room in an SF Victorian private home. It has 2 twin beds--normal rates: one person ($135/night) or 2 (add $80/night). Comfortable and inviting! Plenty of art, books and light! Holiday Special Discount Rates and other seasonal changes will apply. See calendar for daily rates. Currently has 2 twin beds. Please note, if you have a second person, you will be charged $80 per night for that person.', lat: 37.766457, lng: -122.4223524, street_address: '1906 Mission St', city: 'San Francisco', state: 'CA', zip: 94107, price: 436, occupancy: 4, date: new Date() },
        { _id: spotsIds[28], images: [img1Ids[28], img2Ids[28]], host_id: 29, name: 'Petite Auberge - Deluxe King with Fireplace', description: 'A charming French country inn - in the heart of San FranciscoThe rich and detailed design of San Francisco s Petite Auberge welcomes you to a world of French provincial enchantment. Nestled in the heart of the popular neighborhood of Nob Hill, the Petite Auberge is one of best-kept secrets in San Francisco. The hotel is a popular destination for regional travelers seeking relaxation in the city, as well as international travelers looking for a unique hotel experience during their travels. Our special boutique Bed and Breakfast reside just blocks away from the Bay Area’s best shopping, shows, museums and popular attractions.', lat: 37.7593026, lng: -122.4211643, street_address: '2361 Mission St', city: 'San Francisco', state: 'CA', zip: 94107, price: 481, occupancy: 4, date: new Date() },
        { _id: spotsIds[29], images: [img1Ids[29], img2Ids[29]], host_id: 30, name: 'Room @ Golden Gate Bridge, Ocean Beaches & Parks.', description: 'The room is newly painted.  Wardrobe with huge glass doors.  New sofa bed, 70   long.  Full size mattress.    New 43  Sharp Ultra HDTV with Roku.WiFi.      Blinds.Alarm.8 ceiling spots with 4 lamps chandelier make the room super bright.  I run a limo company and can do SFO transfer for $85.City tours and Wine tours to Napa and Sonoma available.5 blocks to China Beach and Baker Beach.0.8 miles to Legion of Honor Museum.1 mile to the Golden Gate Park.2 miles to the GG Bridge.  One person only.', lat: 37.7793642, lng: -122.4002296, street_address: '504 4th St', city: 'San Francisco', state: 'CA', zip: 94105, price: 511, occupancy: 1, date: new Date() },
        { _id: spotsIds[30], images: [img1Ids[30], img2Ids[30]], host_id: 31, name: '❤5Min to GG Park &Haight-Breakfast-Parking Avail', description: 'Our home was built in 1912. It has quaint Victorian features like crown moldings, rounded ceiling, picture frame walls & more. Our decor reflects our diverse background of England, Vietnam and our love of the ocean.Many of the furniture & art work are hand - made by us.Guests have said our home feels peaceful, warm, and relaxing.We ❤️ our home and we d love to share it with you.', lat: 37.7788559, lng: -122.3946075, street_address: '701 3rd St', city: 'San Francisco', state: 'CA', zip: 94105, price: 376, occupancy: 3, date: new Date() },
        { _id: spotsIds[31], images: [img1Ids[31], img2Ids[31]], host_id: 32, name: 'Delmar Street guest suite w/ panoramic city views', description: 'Private, light-filled, quiet, top studio in a classic Edwardian with expansive views of San Francisco and a rooftop deck. Located between charming Cole Valley, historic Haight-Ashbury, and within walking distance of Golden Gate Park and UCSF.', lat: 37.7822079, lng: -122.4070206, street_address: '888 Howard St', city: 'San Francisco', state: 'CA', zip: 94105, price: 296, occupancy: 2, date: new Date() },
        { _id: spotsIds[32], images: [img1Ids[32], img2Ids[32]], host_id: 33, name: 'Quiet, Airy Room One Block from Golden Gate Park', description: 'Quiet, airy room in the back of the house. Connects directly to shared sunroom and backyard.', lat: 37.7781198, lng: -122.405848, street_address: '966 Harrison St', city: 'San Francisco', state: 'CA', zip: 94105, price: 481, occupancy: 3, date: new Date() },
        { _id: spotsIds[33], images: [img1Ids[33], img2Ids[33]], host_id: 34, name: 'Cozy Room One Block from Golden Gate Park', description: 'Cozy room in the Inner Richmond District. A quiet residential home walking distance to Golden Gate Park, shops, restaurants, bars', lat: 37.7792353, lng: -122.4091225, street_address: '226 6th St', city: 'San Francisco', state: 'CA', zip: 94105, price: 550, occupancy: 2, date: new Date() },
        { _id: spotsIds[34], images: [img1Ids[34], img2Ids[34]], host_id: 35, name: 'In the heart of Haight/Ashbury # 3 STR', description: 'Planning a trip to San Francisco? Then why not stay in the heart of the city in the historic Haight Ashbury district. Located in a classic 1907 Victorian building. We have a fully furnished unit available for BNB guests. We have 4 bed rooms as #3, #4, #5 and # 6 on level 3 in the Victorian flat. These private rooms can be booked separately by individuals or the whole flat can be booked for a party of 8 people. There is a large common kitchen and 1.5 bath-room . There is also a green room behind the kitchen leading to a deck and stairs to the large back-yard. Please check out the pictures of the flat and the individual rooms, the common bath-room, kitchen and common areas. ', lat: 37.77735, lng: -122.4104721, street_address: '259 7th St', city: 'San Francisco', state: 'CA', zip: 94105, price: 411, occupancy: 2, date: new Date() },
        { _id: spotsIds[35], images: [img1Ids[35], img2Ids[35]], host_id: 36, name: 'Luxury Interior Designer’s GH/Apt - Pac Heights', description: 'Surround yourself in luxury in this beautiful designer 1-bedroom - it s sexy, contemporary and luxurious. Close to some of the most coveted food in the city: Ariscault Bakery (named best croissant in the world by Bon Appetit), Authentic Chinese, Burmese, Taiwanese, Dim Sum, Giorgio s Pizza (institution).Close to GG Park, Museums, Presidio. Easy access to downtown/Moscone. Separate entrance. Walk to coffee, grocery, etc. If you re looking for a true SF experience-this is it!', lat: 37.7756659, lng: -122.410804, street_address: '10 Hallam St', city: 'San Francisco', state: 'CA', zip: 94105, price: 368, occupancy: 3, date: new Date() },
        { _id: spotsIds[36], images: [img1Ids[36], img2Ids[36]], host_id: 37, name: 'Victorian in the heart of Castro II', description: 'Located in the heart of Castro, our unit is a renovated, private room in a historic Victorian. Experience the charm and elegance of a bygone era, while enjoying the modern comforts of a recent renovation. Close to great cafes, shops and Muni metro.', lat: 37.7788706, lng: -122.4120651, street_address: '121 7th St', city: 'San Francisco', state: 'CA', zip: 94105, price: 275, occupancy: 2, date: new Date() },
        { _id: spotsIds[37], images: [img1Ids[37], img2Ids[37]], host_id: 38, name: 'Red Victorian - Private room w/sink, Tea Garden', description: 'The  Japanese Tea Garden  is a private bedroom located in the historic Red Victorian, on Haight-Ashbury.The Red Victorian is an experimental community run hotel that offers unique guest experiences. While here, we invite you to attend events: lectures & talks, skill shares, music nights, art shows!', lat: 37.7781588, lng: -122.4172863, street_address: '1231 Market St', city: 'San Francisco', state: 'CA', zip: 94105, price: 315, occupancy: 3, date: new Date() },
        { _id: spotsIds[38], images: [img1Ids[38], img2Ids[38]], host_id: 39, name: 'Garden View, Inner Sunset, Golden Gate Park, UCSF', description: '5 minute walk to Golden Gate Park, Botanical Garden, Japanese Tea Garden and De Young Museum are down the street. Post office, banks, affordable restaurants, public transportation and markets are nearby. Cole Valley & Haight Ashbury are adjacent  micro-neighborhoods .', lat: 37.775472, lng: -122.412244, street_address: '1188 Folsom St', city: 'San Francisco', state: 'CA', zip: 94105, price: 527, occupancy: 3, date: new Date() },
        { _id: spotsIds[39], images: [img1Ids[39], img2Ids[39]], host_id: 40, name: '250 Sq Ft Cozy Private Bedroom by Ocean Beach', description: 'New renovated Cozy with Separated Entrance,        Sunny & Convenient to Golden Gate Park.      Close to beaches, G Gate Park, G Gate Bridge, groceries, cafes, restaurants on city - block for memorable vacation / business / retreat.We are located in Sutro Heights our neighborhood is approx 30 mins from downtown.and are within a 15 minutes of the French Legion of Honor Museum, the Academy of Sciences Museum, and the DeYoung Museum.One block away, a $2.75 bus ride will take you directly downtown in 20 minutes.', lat: 37.7865004, lng: -122.4117595, street_address: '312 Mason St', city: 'San Francisco', state: 'CA', zip: 94103, price: 359, occupancy: 4, date: new Date() },
        { _id: spotsIds[40], images: [img1Ids[40], img2Ids[40]], host_id: 41, name: '311C Private Room in Super Convenient Area, Room C', description: 'My place is located at one of the most convenient neighborhood in San Francisco. It is located on 4th Ave and Clement street in Richmond district, with all the shops, restaurants, supermarkets, banks, bars and clubs right down the street!It is also close to everywhere:        - 4 mins drive / 4 blocks to Golden Gate Park;        - 6 mins drive to Golden Gate Bridge;        - 14 mins drive to Downtown SF;        - 20 mins drive to Fisherman s Wharf.', lat: 37.7884051, lng: -122.4127731, street_address: '515 Mason St', city: 'San Francisco', state: 'CA', zip: 94103, price: 409, occupancy: 4, date: new Date() },
        { _id: spotsIds[41], images: [img1Ids[41], img2Ids[41]], host_id: 42, name: 'Red Victorian - Bunk #4 in shared Poster Room', description: 'This listing is for a beautiful bunk space in our shared  Poster  room, part of the historic Red Victorian near Haight-Ashbury. Bunk #4 is a BOTTOM BUNK. The Red Victorian is an experimental community run hotel that offers unique guest experiences.While here, we invite you to attend events: lectures & talks, skill shares, music nights, art shows!', lat: 37.7891412, lng: -122.4094101, street_address: '345 Stockton St', city: 'San Francisco', state: 'CA', zip: 94103, price: 418, occupancy: 2, date: new Date() },
        { _id: spotsIds[42], images: [img1Ids[42], img2Ids[42]], host_id: 43, name: '311E Private Room in Super Convenient Area, Room E', description: 'My place is located at one of the most convenient neighborhood in San Francisco. It is located on 4th Ave and Clement street in Richmond district, with all the shops, restaurants, supermarkets, banks, bars and clubs right down the street!            It is also close to everywhere            - 4 mins drive / 4 blocks to Golden Gate Park            - 6 mins drive to Golden Gate Bridge            - 14 mins drive to Downtown SF            - 20 mins drive to Fisherman s Wharf.', lat: 37.7864234, lng: -122.4052948, street_address: '50 3rd St', city: 'San Francisco', state: 'CA', zip: 94103, price: 542, occupancy: 3, date: new Date() },
        { _id: spotsIds[43], images: [img1Ids[43], img2Ids[43]], host_id: 44, name: 'Castro Victorian Charm', description: 'This is an elegant updated Victorian. It boasts 3 bedrooms, 2 full baths in 1700 sq.ft. 12 foot ceilings and many period details show off this gorgeous large flat. You will be pampered with your private bathroom. In bedroom flat screen smart TV with Netflix. Soak in the tub with jets or shower. The location is one of San Francisco s finest, 1/2 block from the underground subway and buses in the vibrant Castro neighborhood. Wireless internet and cable TV included. Minimum stay is 2 nights.', lat: 37.7884503, lng: -122.4042389, street_address: '2 New Montgomery St', city: 'San Francisco', state: 'CA', zip: 94103, price: 422, occupancy: 4, date: new Date() },
        { _id: spotsIds[44], images: [img1Ids[44], img2Ids[44]], host_id: 45, name: 'SF Stylish Apt near Presidio & GG Bridge w/ Garage', description: 'Located in Richmond District, voted SF Best Dining Neighborhood by both Eater & Thrillist              • Remodeled 1, 400 sf apt              • Walk Score 94: Easy access to Presidio, GG Bridge & GG Park, Baker Beach, Lands End trail, etc              • Surrounded by renowned restaurants              • Drive to downtown / airport / Muir Woods about 30 min, Napa 1 hr              • Onsite garage for 1 vehicle up to 6 ft tall              • Fully equipped, stocked kitchen              • Washer & dryer              • Fast Internet with 320 MBPS Wi - Fi              • HDTV w Netflix, Prime Videos, Sling TV, YouTube, etc.', lat: 37.7924577, lng: -122.4029797, street_address: '222 Sansome St', city: 'San Francisco', state: 'CA', zip: 94103, price: 527, occupancy: 2, date: new Date() },
        { _id: spotsIds[45], images: [img1Ids[45], img2Ids[45]], host_id: 46, name: 'Home in the vibrant NOPA neighborhood w/Parking!', description: 'Just three blocks from the city epicenter and a 1-minute walk to a major bus line that will take you to downtown, Golden Gate Park or Ocean Beach in just 10 minutes! Located in one of the best neighborhoods in SF, with only a 5-minute walk to top-rated restaurants, bars, shopping, three major grocery stores as well as the historic Golden Gate Park. Message me with any questions. I m an SF native who loves to travel.', lat: 37.7946729, lng: -122.403038, street_address: '333 Battery St', city: 'San Francisco', state: 'CA', zip: 94103, price: 254, occupancy: 2, date: new Date() },
        { _id: spotsIds[46], images: [img1Ids[46], img2Ids[46]], host_id: 47, name: 'Just three blocks from the city', description: 'Full of light, clean and very spacious on the top floor of a newly updated Edwardian building built in 1910 and just steps away from the famous Haight and Ashbury streets. You ll have plenty of privacy to slumber in this largely spread out apartment with 3 private bedrooms, 2 living / hangout rooms, and a newly updated and light filled kitchen.', lat: 37.7982726, lng: -122.4075516, street_address: '494 Broadway', city: 'San Francisco', state: 'CA', zip: 94103, price: 442, occupancy: 2, date: new Date() },
        { _id: spotsIds[47], images: [img1Ids[47], img2Ids[47]], host_id: 48, name: 'Cozy Room in Sight of the Sea', description: 'PRIVATE BATH: The room has same floor exclusive private shower/bathroom and Atrium. Peak outside these bedroom windows: drink in the Pacific and Ocean Beach, or gaze upon a spacious new hot tub to soak out your weary day from exploring the city.', lat: 37.7974662, lng: -122.4100349, street_address: '661 Broadway', city: 'San Francisco', state: 'CA', zip: 94103, price: 259, occupancy: 2, date: new Date() },
        { _id: spotsIds[48], images: [img1Ids[48], img2Ids[48]], host_id: 49, name: '250 Sq Ft Cozy Private Bedroom by Ocean Beach', description: 'New renovated Cozy with Separated Entrance,                  Sunny & Convenient to Golden Gate Park.                  Close to beaches, G Gate Park, G Gate Bridge, groceries, cafes, restaurants on city - block for memorable vacation / business / retreat.We are located in Sutro Heights our neighborhood is approx 30 mins from downtown.and are within a 15 minutes of the French Legion of Honor Museum, the Academy of Sciences Museum, and the DeYoung Museum.One block away, a $2.75 bus ride will take you directly downtown in 20 minutes.', lat: 37.788844, lng: -122.412669, street_address: '609 Sutter St', city: 'San Francisco', state: 'CA', zip: 94103, price: 321, occupancy: 2, date: new Date() },
        { _id: spotsIds[49], images: [img1Ids[49], img2Ids[49]], host_id: 50, name: 'Charming Private bedroom 2 by GGP and Ocean Beach', description: 'Enjoy a luxurious stay in this charming, private house with living room, kitchen and 1.5 bathrooms. Walk to the Golden Gate Park and Ocean beach, 24/7 Safeway, Beach Chalet, Cliff House and other restaurants. No parties. No pets. No smoking.', lat: 37.7854871, lng: -122.4068879, street_address: '780 Mission St,', city: 'San Francisco', state: 'CA', zip: 94103, price: 538, occupancy: 4, date: new Date() },
      ], (errors, spots) => {
        Image.remove({}).then(() => {
          Image.create(
            [
              { _id: img1Ids[0], spot: spotsIds[0], img_url: 'https://a0.muscache.com/im/pictures/a38c2d1c-98cf-48fb-9a87-6c1313dca07c.jpg?aki_policy=xx_large' },
              { _id: img2Ids[0], spot: spotsIds[0], img_url: 'https://a0.muscache.com/im/pictures/9b4fd4b2-5f0e-4515-a0e3-8d0dba62083c.jpg?aki_policy=large' },
              { _id: img1Ids[1], spot: spotsIds[1], img_url: 'https://a0.muscache.com/im/pictures/2220269/d7ad9746_original.jpg?aki_policy=xx_large' },
              { _id: img2Ids[1], spot: spotsIds[1], img_url: 'https://a0.muscache.com/im/pictures/2220282/c715a885_original.jpg?aki_policy=large' },
              { _id: img1Ids[2], spot: spotsIds[2], img_url: 'https://a0.muscache.com/im/pictures/7afaf359-9c55-4d09-a059-62761757a4dc.jpg?aki_policy=xx_large' },
              { _id: img2Ids[2], spot: spotsIds[2], img_url: 'https://a0.muscache.com/im/pictures/167fcb91-7e02-4828-af7c-6314bdfaa54b.jpg?aki_policy=x_large' },
              { _id: img1Ids[3], spot: spotsIds[3], img_url: 'https://a0.muscache.com/im/pictures/adfa484c-b15a-45d6-8aed-8a5f714f4792.jpg?aki_policy=xx_large' },
              { _id: img2Ids[3], spot: spotsIds[3], img_url: 'https://a0.muscache.com/im/pictures/d5d87527-47f4-41b8-929c-b3ebf1d32d84.jpg?aki_policy=large' },
              { _id: img1Ids[4], spot: spotsIds[4], img_url: 'https://a0.muscache.com/im/pictures/84d16379-b0b7-41e9-94c5-1f6a952f5b2b.jpg?aki_policy=xx_large' },
              { _id: img2Ids[4], spot: spotsIds[4], img_url: 'https://a0.muscache.com/im/pictures/ce17cae7-fe70-4441-80a3-1a9235c0f34c.jpg?aki_policy=large' },
              { _id: img1Ids[5], spot: spotsIds[5], img_url: 'https://a0.muscache.com/im/pictures/8acae9d2-33b8-45a4-af7b-a578eafdc179.jpg?aki_policy=xx_large' },
              { _id: img2Ids[5], spot: spotsIds[5], img_url: 'https://a0.muscache.com/im/pictures/2d964ca8-11ad-4d9d-a199-a0f6ca160a25.jpg?aki_policy=large' },
              { _id: img1Ids[6], spot: spotsIds[6], img_url: 'https://a0.muscache.com/im/pictures/72291744/332ccfe5_original.jpg?aki_policy=xx_large' },
              { _id: img2Ids[6], spot: spotsIds[6], img_url: 'https://a0.muscache.com/im/pictures/dacfa153-e35e-4fc5-af0d-85aa9851545b.jpg?aki_policy=large' },
              { _id: img1Ids[7], spot: spotsIds[7], img_url: 'https://a0.muscache.com/im/pictures/604054de-b03c-4a8a-a7c4-8d45c95c1dbb.jpg?aki_policy=xx_large' },
              { _id: img2Ids[7], spot: spotsIds[7], img_url: 'https://a0.muscache.com/im/pictures/be4fa584-0cce-454d-a126-f42d4261c860.jpg?aki_policy=large' },
              { _id: img1Ids[8], spot: spotsIds[8], img_url: 'https://a0.muscache.com/im/pictures/6b465fb5-1859-458b-ada8-d9ef6f11f576.jpg?aki_policy=xx_large' },
              { _id: img2Ids[8], spot: spotsIds[8], img_url: 'https://a0.muscache.com/im/pictures/7f6b2be2-3308-4582-9a7c-9aad22f4a14a.jpg?aki_policy=large' },
              { _id: img1Ids[9], spot: spotsIds[9], img_url: 'https://a0.muscache.com/im/pictures/8912204/5e371cf5_original.jpg?aki_policy=xx_large' },
              { _id: img2Ids[9], spot: spotsIds[9], img_url: 'https://a0.muscache.com/im/pictures/13180796/cfd36232_original.jpg?aki_policy=large' },
              { _id: img1Ids[10], spot: spotsIds[10], img_url: 'https://a0.muscache.com/im/pictures/bb0f2350-25cf-4dd5-9634-01191830a388.jpg?aki_policy=xx_large' },
              { _id: img2Ids[10], spot: spotsIds[10], img_url: 'https://a0.muscache.com/im/pictures/94844d24-6e27-48fb-855a-b59148608769.jpg?aki_policy=large' },
              { _id: img1Ids[11], spot: spotsIds[11], img_url: 'https://a0.muscache.com/im/pictures/106339718/58fbf9d4_original.jpg?aki_policy=xx_large' },
              { _id: img2Ids[11], spot: spotsIds[11], img_url: 'https://a0.muscache.com/im/pictures/106340134/64bcd6c4_original.jpg?aki_policy=large' },
              { _id: img1Ids[12], spot: spotsIds[12], img_url: 'https://a0.muscache.com/im/pictures/e3dd17b4-2520-41c0-ae59-6a0d93e53efc.jpg?aki_policy=xx_large' },
              { _id: img2Ids[12], spot: spotsIds[12], img_url: 'https://a0.muscache.com/im/pictures/69df4f1a-d15d-46c4-b16c-7137b3b5a9b1.jpg?aki_policy=large' },
              { _id: img1Ids[13], spot: spotsIds[13], img_url: 'https://a0.muscache.com/im/pictures/92e17d74-b960-4651-bb1d-d1b8d7c82b24.jpg?aki_policy=xx_large' },
              { _id: img2Ids[13], spot: spotsIds[13], img_url: 'https://a0.muscache.com/im/pictures/157616c2-94d0-4c4c-ba32-d5f50d194d30.jpg?aki_policy=large' },
              { _id: img1Ids[14], spot: spotsIds[14], img_url: 'https://a0.muscache.com/im/pictures/7f46a54b-a214-4d3a-b6b7-0842d42449aa.jpg?aki_policy=xx_large' },
              { _id: img2Ids[14], spot: spotsIds[14], img_url: 'https://a0.muscache.com/im/pictures/6623176c-894e-4214-8b29-dfda5d122c18.jpg?aki_policy=large' },
              { _id: img1Ids[15], spot: spotsIds[15], img_url: 'https://a0.muscache.com/im/pictures/1afedf9e-7731-4bf9-a952-20f99791a2c3.jpg?aki_policy=xx_large' },
              { _id: img2Ids[15], spot: spotsIds[15], img_url: 'https://a0.muscache.com/im/pictures/fcf27b73-c3cf-4952-8bed-d8206f5484ac.jpg?aki_policy=large' },
              { _id: img1Ids[16], spot: spotsIds[16], img_url: 'https://a0.muscache.com/im/pictures/2853aa49-cf6f-478f-89ec-5e50a3019a1e.jpg?aki_policy=xx_large' },
              { _id: img2Ids[16], spot: spotsIds[16], img_url: 'https://a0.muscache.com/im/pictures/90326bbb-aa41-44b1-aa46-a824d6dda477.jpg?aki_policy=large' },
              { _id: img1Ids[17], spot: spotsIds[17], img_url: 'https://a0.muscache.com/im/pictures/79060294/fc59ac10_original.jpg?aki_policy=xx_large' },
              { _id: img2Ids[17], spot: spotsIds[17], img_url: 'https://a0.muscache.com/im/pictures/80027531/e53f1279_original.jpg?aki_policy=large' },
              { _id: img1Ids[18], spot: spotsIds[18], img_url: 'https://a0.muscache.com/im/pictures/9781b845-094e-453d-94e9-70dc695e2839.jpg?aki_policy=xx_large' },
              { _id: img2Ids[18], spot: spotsIds[18], img_url: 'https://a0.muscache.com/im/pictures/b1f92a45-c852-4e20-a059-aa84474458ec.jpg?aki_policy=large' },
              { _id: img1Ids[19], spot: spotsIds[19], img_url: 'https://a0.muscache.com/im/pictures/de3fea33-d8f5-434e-8366-8c85c84ce8ea.jpg?aki_policy=xx_large' },
              { _id: img2Ids[19], spot: spotsIds[19], img_url: 'https://a0.muscache.com/im/pictures/cc2a23f3-d016-43ea-a7ab-553244ea7de4.jpg?aki_policy=large' },
              { _id: img1Ids[20], spot: spotsIds[20], img_url: 'https://a0.muscache.com/im/pictures/124eb9f5-def6-4982-9ea2-3479175e9320.jpg?aki_policy=xx_large' },
              { _id: img2Ids[20], spot: spotsIds[20], img_url: 'https://a0.muscache.com/im/pictures/7a11e03e-e40f-4c6a-9d71-1dc8aad18c72.jpg?aki_policy=large' },
              { _id: img1Ids[21], spot: spotsIds[21], img_url: 'https://a0.muscache.com/im/pictures/18f246cb-5338-4d6e-b0a4-395eae357480.jpg?aki_policy=xx_large' },
              { _id: img2Ids[21], spot: spotsIds[21], img_url: 'https://a0.muscache.com/im/pictures/84379100/d10e50fa_original.jpg?aki_policy=large' },
              { _id: img1Ids[22], spot: spotsIds[22], img_url: 'https://a0.muscache.com/im/pictures/b3cdb5ea-c7b8-4fd8-bd48-537b33d08499.jpg?aki_policy=xx_large' },
              { _id: img2Ids[22], spot: spotsIds[22], img_url: 'https://a0.muscache.com/im/pictures/f0253447-cfe9-43c6-8b65-81fc2213b410.jpg?aki_policy=large' },
              { _id: img1Ids[23], spot: spotsIds[23], img_url: 'https://a0.muscache.com/im/pictures/fef182ea-71a4-4e5e-8f80-eb37c756c5de.jpg?aki_policy=xx_large' },
              { _id: img2Ids[23], spot: spotsIds[23], img_url: 'https://a0.muscache.com/im/pictures/66e13773-60c1-4a54-a1b5-d8fc6cc70af1.jpg?aki_policy=large' },
              { _id: img1Ids[24], spot: spotsIds[24], img_url: 'https://a0.muscache.com/im/pictures/6b6ea25c-7f08-4350-929a-062012ae8be3.jpg?aki_policy=large' },
              { _id: img2Ids[24], spot: spotsIds[24], img_url: 'https://a0.muscache.com/im/pictures/48a43284-8fe6-4765-a6d8-de6f139ffc8d.jpg?aki_policy=large' },
              { _id: img1Ids[25], spot: spotsIds[25], img_url: 'https://a0.muscache.com/im/pictures/07d2ba4c-ff0f-40ec-9b01-5e23787c8a74.jpg?aki_policy=xx_large' },
              { _id: img2Ids[25], spot: spotsIds[25], img_url: 'https://a0.muscache.com/im/pictures/225b84f7-951d-4f5f-8be2-8cf1b6546371.jpg?aki_policy=large' },
              { _id: img1Ids[26], spot: spotsIds[26], img_url: 'https://a0.muscache.com/im/pictures/73735d55-a62a-4af4-98c5-1a3abcaa58f2.jpg?aki_policy=xx_large' },
              { _id: img2Ids[26], spot: spotsIds[26], img_url: 'https://a0.muscache.com/im/pictures/086f070e-5dec-4659-acc0-7e435b98dacc.jpg?aki_policy=large' },
              { _id: img1Ids[27], spot: spotsIds[27], img_url: 'https://a0.muscache.com/im/pictures/e4f60242-783b-420f-9911-817d2c6e55cb.jpg?aki_policy=xx_large' },
              { _id: img2Ids[27], spot: spotsIds[27], img_url: 'https://a0.muscache.com/im/pictures/b484e2fe-8c21-4a8f-a777-cc3b7086c297.jpg?aki_policy=large' },
              { _id: img1Ids[28], spot: spotsIds[28], img_url: 'https://a0.muscache.com/im/pictures/811f78ee-a38d-47a8-ae01-667549f26264.jpg?aki_policy=xx_large' },
              { _id: img2Ids[28], spot: spotsIds[28], img_url: 'https://a0.muscache.com/im/pictures/d88062b8-7bfd-4010-b4fd-b46a58e3e8e4.jpg?aki_policy=large' },
              { _id: img1Ids[29], spot: spotsIds[29], img_url: 'https://a0.muscache.com/im/pictures/842a4a55-65bc-4347-9d8f-740dd382ca95.jpg?aki_policy=large' },
              { _id: img2Ids[29], spot: spotsIds[29], img_url: 'https://a0.muscache.com/im/pictures/cd113e92-7b62-4c51-8ecc-d11eef194f94.jpg?aki_policy=large' },
              { _id: img1Ids[30], spot: spotsIds[30], img_url: 'https://a0.muscache.com/im/pictures/be601476-ac49-4f5c-90f5-d3519448fc03.jpg?aki_policy=large' },
              { _id: img2Ids[30], spot: spotsIds[30], img_url: 'https://a0.muscache.com/im/pictures/a1ba9363-569f-4ecf-81a4-c7cd659e09ad.jpg?aki_policy=large' },
              { _id: img1Ids[31], spot: spotsIds[31], img_url: 'https://a0.muscache.com/im/pictures/291d14ff-af0c-4cc9-8dcb-418d78aaed32.jpg?aki_policy=xx_large' },
              { _id: img2Ids[31], spot: spotsIds[31], img_url: 'https://a0.muscache.com/im/pictures/ce3e00b0-8b84-412e-8a25-9eeb01ff9b56.jpg?aki_policy=large' },
              { _id: img1Ids[32], spot: spotsIds[32], img_url: 'https://a0.muscache.com/im/pictures/9c5d4b3d-6afb-43f9-b0cf-29572bf52e3c.jpg?aki_policy=large' },
              { _id: img2Ids[32], spot: spotsIds[32], img_url: 'https://a0.muscache.com/im/pictures/7f01cff7-50db-48b7-be21-c214cbf540a9.jpg?aki_policy=large' },
              { _id: img1Ids[33], spot: spotsIds[33], img_url: 'https://a0.muscache.com/im/pictures/fa7cd4a6-f019-4339-a364-8b9fa806df21.jpg?aki_policy=large' },
              { _id: img2Ids[33], spot: spotsIds[33], img_url: 'https://a0.muscache.com/im/pictures/a241a52a-3171-4465-87e4-3b751ab643cd.jpg?aki_policy=large' },
              { _id: img1Ids[34], spot: spotsIds[34], img_url: 'https://a0.muscache.com/im/pictures/da76bec7-4fde-4cff-a93f-ffcc5ccbddc8.jpg?aki_policy=large' },
              { _id: img2Ids[34], spot: spotsIds[34], img_url: 'https://a0.muscache.com/im/pictures/a7631c9e-49a7-49bb-bd66-5df3042dcbd3.jpg?aki_policy=large' },
              { _id: img1Ids[35], spot: spotsIds[35], img_url: 'https://a0.muscache.com/im/pictures/838c6bed-870c-422c-9a55-be3320c47350.jpg?aki_policy=xx_large' },
              { _id: img2Ids[35], spot: spotsIds[35], img_url: 'https://a0.muscache.com/im/pictures/7d418147-8cf4-4d06-8d2c-dbbf1fa427f5.jpg?aki_policy=large' },
              { _id: img1Ids[36], spot: spotsIds[36], img_url: 'https://a0.muscache.com/im/pictures/37162895-38f5-4564-9d81-18eff594b571.jpg?aki_policy=xx_large' },
              { _id: img2Ids[36], spot: spotsIds[36], img_url: 'https://a0.muscache.com/im/pictures/022fb44e-5d83-42d1-b70e-23f985a7d45b.jpg?aki_policy=large' },
              { _id: img1Ids[37], spot: spotsIds[37], img_url: 'https://a0.muscache.com/im/pictures/f663989d-f391-482b-a32e-83bdcd529705.jpg?aki_policy=xx_large' },
              { _id: img2Ids[37], spot: spotsIds[37], img_url: 'https://a0.muscache.com/im/pictures/f4edf470-f85f-4fb7-b529-66cf350b6881.jpg?aki_policy=large' },
              { _id: img1Ids[38], spot: spotsIds[38], img_url: 'https://a0.muscache.com/im/pictures/96dbf301-a100-4d01-bf95-ace0edf00172.jpg?aki_policy=xx_large' },
              { _id: img2Ids[38], spot: spotsIds[38], img_url: 'https://a0.muscache.com/im/pictures/42791880-96bf-4777-8e70-8a3963e4f86a.jpg?aki_policy=large' },
              { _id: img1Ids[39], spot: spotsIds[39], img_url: 'https://a0.muscache.com/im/pictures/ceda97e1-015c-4acf-be5f-27d221c8b881.jpg?aki_policy=xx_large' },
              { _id: img2Ids[39], spot: spotsIds[39], img_url: 'https://a0.muscache.com/im/pictures/1587f388-0a34-41d0-ac54-dad0a87fda77.jpg?aki_policy=large' },
              { _id: img1Ids[40], spot: spotsIds[40], img_url: 'https://a0.muscache.com/im/pictures/d88710d8-e7de-4d94-81cd-e74e53ac526c.jpg?aki_policy=xx_large' },
              { _id: img2Ids[40], spot: spotsIds[40], img_url: 'https://a0.muscache.com/im/pictures/6507a48a-1868-489c-9b1e-7063727e8b43.jpg?aki_policy=large' },
              { _id: img1Ids[41], spot: spotsIds[41], img_url: 'https://a0.muscache.com/im/pictures/5bed0917-de67-4764-aed6-79e2eba1bc01.jpg?aki_policy=xx_large' },
              { _id: img2Ids[41], spot: spotsIds[41], img_url: 'https://a0.muscache.com/im/pictures/48e1a76f-fd9d-4477-8844-3ccbb9fb7226.jpg?aki_policy=large' },
              { _id: img1Ids[42], spot: spotsIds[42], img_url: 'https://a0.muscache.com/im/pictures/83a73370-5877-4717-bab9-70daa746b06f.jpg?aki_policy=large' },
              { _id: img2Ids[42], spot: spotsIds[42], img_url: 'https://a0.muscache.com/im/pictures/48256da3-7d7d-4fe3-b905-2844b7318347.jpg?aki_policy=large' },
              { _id: img1Ids[43], spot: spotsIds[43], img_url: 'https://a0.muscache.com/im/pictures/df15e025-f054-476e-ad10-516fd14873fa.jpg?aki_policy=large' },
              { _id: img2Ids[43], spot: spotsIds[43], img_url: 'https://a0.muscache.com/im/pictures/ec43f0af-dfe5-42c7-a4e1-7a23850b4f20.jpg?aki_policy=large' },
              { _id: img1Ids[44], spot: spotsIds[44], img_url: 'https://a0.muscache.com/im/pictures/1920bc3e-a451-4595-a68c-255e72dcd459.jpg?aki_policy=large' },
              { _id: img2Ids[44], spot: spotsIds[44], img_url: 'https://a0.muscache.com/im/pictures/e43a76cb-3925-45a5-8831-f51e28318b37.jpg?aki_policy=large' },
              { _id: img1Ids[45], spot: spotsIds[45], img_url: 'https://a0.muscache.com/im/pictures/b0ac6ce7-420c-4598-86b9-1007fddbf077.jpg?aki_policy=large' },
              { _id: img2Ids[45], spot: spotsIds[45], img_url: 'https://a0.muscache.com/im/pictures/873dfa0c-27e8-4243-9b11-eebcfc45af48.jpg?aki_policy=large' },
              { _id: img1Ids[46], spot: spotsIds[46], img_url: 'https://a0.muscache.com/im/pictures/9093ba5c-d755-4dbe-b441-ff74a5abeca7.jpg?aki_policy=large' },
              { _id: img2Ids[46], spot: spotsIds[46], img_url: 'https://a0.muscache.com/im/pictures/87c0d2fd-2d8e-46bc-b9c8-efbbab9cc420.jpg?aki_policy=large' },
              { _id: img1Ids[47], spot: spotsIds[47], img_url: 'https://a0.muscache.com/im/pictures/c9f06172-4dff-456d-8ea6-97b6ae9988ea.jpg?aki_policy=large' },
              { _id: img2Ids[47], spot: spotsIds[47], img_url: 'https://a0.muscache.com/im/pictures/30b97f59-97bf-4be7-8594-a742be5fd614.jpg?aki_policy=large' },
              { _id: img1Ids[48], spot: spotsIds[48], img_url: 'https://a0.muscache.com/im/pictures/9fb7a438-1c64-43be-9f4e-b8cac07a8dd5.jpg?aki_policy=large' },
              { _id: img2Ids[48], spot: spotsIds[48], img_url: 'https://a0.muscache.com/im/pictures/2d9a3426-4698-4142-b8a8-2db26961cb88.jpg?aki_policy=large' },
              { _id: img1Ids[49], spot: spotsIds[49], img_url: 'https://a0.muscache.com/im/pictures/96291ab3-b6dc-4dbf-a49c-3cdad28baeb3.jpg?aki_policy=xx_large' },
              { _id: img2Ids[49], spot: spotsIds[49], img_url: 'https://a0.muscache.com/im/pictures/1e3471e6-a197-4a24-8a1e-fd026500226b.jpg?aki_policy=large' },
              // { _id: img1Ids[50], spot: spotsIds[50], img_url: 'https://a0.muscache.com/im/pictures/2133a6ee-61f5-47a0-aa0d-1266ca261fc6.jpg?aki_policy=xx_large' },
              // { _id: img2Ids[50], spot: spotsIds[50], img_url: 'https://a0.muscache.com/im/pictures/2aae5da2-bd0b-4587-9f40-08738e7a277d.jpg?aki_policy=x_large' },
            ], (errors, images) => {
              console.log(errors);
              console.log(images);
            }
          )
        })

      }
    )
  })

});